# Generated by Django 6.0.2 on 2026-02-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_age', models.IntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_study', models.CharField(max_length=100)),
            ],
        ),
    ]
